use_frameworks!

platform :ios, '8.0'

target 'ALCBasicComponents_Example' do
  pod 'ALCBasicComponents', :path => '../'

  target 'ALCBasicComponents_Tests' do
    inherit! :search_paths

    
  end
end
